# Generated by Django 4.2.10 on 2024-03-09 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetables', '0003_receipe_receipe_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='receipe_view_count',
            field=models.IntegerField(default=1),
        ),
    ]
